#项目访问端口
server:
  port: 20300
  servlet:
    context-path: /

#Spring整合mysql驱动
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.135.144:3306/intelligent_app?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Wjt2734058
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#------------------mybatis的配置------------------------------
mybatis:
  # 类别名映射包路径
  type-aliases-package: com.intelligent
  # 全局配置
  configuration:
    # 使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    # 使全局的映射器启用或禁用缓存
    cache-enabled: false
    # # 控制台打印sql，包含数据
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 自定义转换器包路径
  type-handlers-package: com.intelligent
  #mapper文件扫包配置
  mapper-locations:
    #加载mapper文件
    - classpath:/mapper/**/*.xml
logging:
  level:
    root: info
    com.example: debug
  file:
    path:log/intelligent-app.log
